### ISSUE TITLE
Stops crawling through posts at 2000 posts

### ISSUE THREAD

**Issue by drmstwizard** [alexwlchan/finduntaggedtumblrposts.com#15] opened 2017-09-22 14:15 UTC
I have tried running the page multiple times on my blog (90,000+ posts) but it always stops crawling at ~1750 posts. Is this a feature of the script or a bug?

**Comment by alexwlchan** [comment] 2017-09-22 14:25
Bug, duplicate of #13 and #14.

It seems to have been broken for a while, I just haven’t had time to get round to fixing it.

**Comment by drmstwizard** [comment] 2017-10-06 03:17
Do you think you will fix it, and/or is the code open to other developers (like XKit)?

**Comment by alexwlchan** [comment] 2017-10-06 05:14
> is the code open to other developers (like XKit)?

All the code for the site is in this repo, I’ve written at least two blog posts explaining how it works (it’s really not complicated), and everything is MIT licensed. So, yes.

**Comment by alexwlchan** [comment] 2018-03-31 18:57
I think this was fixed by 27d74be1309c467c35d030c9c00719dc5ac7e468, please reopen if the issue persists.

**Closed as completed** 2018-03-31 18:57 UTC
